//! Corpus-derived CLDR data for the NumberFormat machinery (plan Cut 2).
//!
//! The pinned test262 fixtures assert exact strings per locale (e.g.
//! `format-significant-digits.js`, `notation-compact-en-US.js`,
//! `signDisplay-currency-de-DE.js`, `formatRange/pt-PT.js`); these tables
//! are the exact entries the corpus exercises — the fixtures ARE the data
//! spec (the same pattern as the `crates/unicode/build.rs` corpus-derived
//! tables and the Cut 1 `data.rs`).

/// The ECMA-402 §16.5.5 Table 30 numbering systems with simple digit
/// mappings, as `(name, first_codepoint)`: the digits are the ten code
/// points `first .. first+9`. `hanidec`/`jpanfin` are the non-contiguous
/// exception (`〇一二三四五六七八九`), handled separately.
pub const NUMBERING_SYSTEM_DIGITS: &[(&str, u32)] = &[
    ("adlm", 0x1E950),
    ("ahom", 0x11730),
    ("arab", 0x0660),
    ("arabext", 0x06F0),
    ("bali", 0x1B50),
    ("beng", 0x09E6),
    ("bhks", 0x11C50),
    ("brah", 0x11066),
    ("cakm", 0x11136),
    ("cham", 0xAA50),
    ("deva", 0x0966),
    ("diak", 0x11950),
    ("fullwide", 0xFF10),
    ("gara", 0x10D40),
    ("gong", 0x11DA0),
    ("gonm", 0x11D50),
    ("gujr", 0x0AE6),
    ("gukh", 0x16130),
    ("guru", 0x0A66),
    ("hmng", 0x16B50),
    ("hmnp", 0x1E140),
    ("java", 0xA9D0),
    ("kali", 0xA900),
    ("kawi", 0x11F50),
    ("khmr", 0x17E0),
    ("knda", 0x0CE6),
    ("krai", 0x16D70),
    ("lana", 0x1A80),
    ("lanatham", 0x1A90),
    ("laoo", 0x0ED0),
    ("latn", 0x0030),
    ("lepc", 0x1C40),
    ("limb", 0x1946),
    ("mathbold", 0x1D7CE),
    ("mathdbl", 0x1D7D8),
    ("mathmono", 0x1D7F6),
    ("mathsanb", 0x1D7EC),
    ("mathsans", 0x1D7E2),
    ("mlym", 0x0D66),
    ("modi", 0x11650),
    ("mong", 0x1810),
    ("mroo", 0x16A60),
    ("mtei", 0xABF0),
    ("mymr", 0x1040),
    ("mymrepka", 0x116DA),
    ("mymrpao", 0x116D0),
    ("mymrshan", 0x1090),
    ("mymrtlng", 0xA9F0),
    ("nagm", 0x1E4F0),
    ("newa", 0x11450),
    ("nkoo", 0x07C0),
    ("olck", 0x1C50),
    ("onao", 0x1E5F1),
    ("orya", 0x0B66),
    ("osma", 0x104A0),
    ("outlined", 0x1CCF0),
    ("rohg", 0x10D30),
    ("saur", 0xA8D0),
    ("segment", 0x1FBF0),
    ("shrd", 0x111D0),
    ("sind", 0x112F0),
    ("sinh", 0x0DE6),
    ("sora", 0x110F0),
    ("sund", 0x1BB0),
    ("sunu", 0x11BF0),
    ("takr", 0x116C0),
    ("talu", 0x19D0),
    ("tamldec", 0x0BE6),
    ("telu", 0x0C66),
    ("thai", 0x0E50),
    ("tibt", 0x0F20),
    ("tirh", 0x114D0),
    ("tnsa", 0x16AC0),
    ("tols", 0x11DE0),
    ("vaii", 0xA620),
    ("wara", 0x118E0),
    ("wcho", 0x1E2F0),
];

/// The `hanidec`/`jpanfin` digits: U+3007, U+4E00, U+4E8C, U+4E09, U+56DB,
/// U+4E94, U+516D, U+4E03, U+516B, U+4E5D.
pub const HANIDEC_DIGITS: [char; 10] = ['〇', '一', '二', '三', '四', '五', '六', '七', '八', '九'];

/// The supported numbering-system identifiers (the ResolveLocale `nu`
/// keyLocaleData list): every Table 30 row plus the remaining testIntl.js
/// `allNumberingSystems()` entries (the `finance`/`native`/`traditio`
/// exclusions of ECMA-402 §16.2.3). `new Intl.Locale("und", {numberingSystem})
/// must round-trip each entry, and the list must be sorted
/// (supportedValuesOf/numberingSystems.js).
pub const SUPPORTED_NUMBERING_SYSTEMS: &[&str] = &[
    "adlm", "ahom", "arab", "arabext", "armn", "armnlow", "bali", "beng", "bhks", "brah", "cakm",
    "cham", "cyrl", "deva", "diak", "ethi", "fullwide", "gara", "geor", "gong", "gonm", "grek",
    "greklow", "gujr", "gukh", "guru", "hanidays", "hanidec", "hans", "hansfin", "hant", "hantfin",
    "hebr", "hmng", "hmnp", "java", "jpan", "jpanfin", "jpanyear", "kali", "kawi", "khmr", "knda",
    "krai", "lana", "lanatham", "laoo", "latn", "lepc", "limb", "mathbold", "mathdbl", "mathmono",
    "mathsanb", "mathsans", "mlym", "modi", "mong", "mroo", "mtei", "mymr", "mymrepka", "mymrpao",
    "mymrshan", "mymrtlng", "nagm", "newa", "nkoo", "olck", "onao", "orya", "osma", "outlined",
    "rohg", "roman", "romanlow", "saur", "segment", "shrd", "sind", "sinh", "sora", "sund", "sunu",
    "takr", "talu", "taml", "tamldec", "telu", "thai", "tibt", "tirh", "tnsa", "tols", "vaii",
    "wara", "wcho",
];

/// ISO 4217 minor units for the currencies that do not use the default of 2
/// (ECMA-402 §16.5.1 CurrencyDigits). CLDR supplement `minorUnit`.
pub fn currency_digits(currency: &str) -> u32 {
    match currency {
        "BIF" | "CLP" | "DJF" | "GNF" | "ISK" | "JPY" | "KMF" | "KRW" | "PYG" | "RWF" | "UGX"
        | "VND" | "VUV" | "XAF" | "XOF" | "XPF" | "XAG" | "XAU" | "XBA" | "XBB" | "XBC" | "XBD"
        | "XDR" | "XPD" | "XPT" | "XSU" | "XUA" | "XXX" => 0,
        "BHD" | "IQD" | "JOD" | "KWD" | "LYD" | "OMR" | "TND" => 3,
        "CLF" | "UYW" => 4,
        _ => 2,
    }
}

/// ISO 4217 currency codes for `Intl.supportedValuesOf("currency")`
/// (availableCanonicalCurrencies; the fixture checks sorted/unique/3-letter).
pub const ISO_4217_CURRENCIES: &[&str] = &[
    "AED", "AFN", "ALL", "AMD", "ANG", "AOA", "ARS", "AUD", "AWG", "AZN", "BAM", "BBD", "BDT",
    "BGN", "BHD", "BIF", "BMD", "BND", "BOB", "BOV", "BRL", "BSD", "BTN", "BWP", "BYN", "BZD",
    "CAD", "CDF", "CHE", "CHF", "CHW", "CLF", "CLP", "CNY", "COP", "COU", "CRC", "CUC", "CUP",
    "CVE", "CZK", "DJF", "DKK", "DOP", "DZD", "EGP", "ERN", "ETB", "EUR", "FJD", "FKP", "GBP",
    "GEL", "GHS", "GIP", "GMD", "GNF", "GTQ", "GYD", "HKD", "HNL", "HRK", "HTG", "HUF", "IDR",
    "ILS", "INR", "IQD", "IRR", "ISK", "JMD", "JOD", "JPY", "KES", "KGS", "KHR", "KMF", "KPW",
    "KRW", "KWD", "KYD", "KZT", "LAK", "LBP", "LKR", "LRD", "LSL", "LYD", "MAD", "MDL", "MGA",
    "MKD", "MMK", "MNT", "MOP", "MRU", "MUR", "MVR", "MWK", "MXN", "MXV", "MYR", "MZN", "NAD",
    "NGN", "NIO", "NOK", "NPR", "NZD", "OMR", "PAB", "PEN", "PGK", "PHP", "PKR", "PLN", "PYG",
    "QAR", "RON", "RSD", "RUB", "RWF", "SAR", "SBD", "SCR", "SDG", "SEK", "SGD", "SHP", "SLE",
    "SLL", "SOS", "SRD", "SSP", "STN", "SVC", "SYP", "SZL", "THB", "TJS", "TMT", "TND", "TOP",
    "TRY", "TTD", "TWD", "TZS", "UAH", "UGX", "USD", "USN", "UYI", "UYU", "UYW", "UZS", "VED",
    "VES", "VND", "VUV", "WST", "XAF", "XAG", "XAU", "XBA", "XBB", "XBC", "XBD", "XCD", "XDR",
    "XOF", "XPD", "XPF", "XPT", "XSU", "XTS", "XUA", "XXX", "YER", "ZAR", "ZMW", "ZWL",
];

/// `Intl.supportedValuesOf("calendar")` (the testIntl.js `allCalendars()` list
/// — the fixture asserts gregory is included, the list is sorted, and every
/// value round-trips through `new Intl.Locale("und", {calendar})`).
pub const SUPPORTED_CALENDARS: &[&str] = &[
    "buddhist",
    "chinese",
    "coptic",
    "dangi",
    "ethioaa",
    "ethiopic",
    "gregory",
    "hebrew",
    "indian",
    "islamic-civil",
    "islamic-tbla",
    "islamic-umalqura",
    "iso8601",
    "japanese",
    "persian",
    "roc",
];

/// `Intl.supportedValuesOf("collation")`: the testIntl.js `allCollations()`
/// list minus `standard`/`search` (the fixture's exclusions).
pub const SUPPORTED_COLLATIONS: &[&str] = &[
    "big5han", "compat", "dict", "direct", "ducet", "emoji", "eor", "gb2312", "phonebk",
    "phonetic", "pinyin", "reformed", "searchjl", "stroke", "trad", "unihan", "zhuyin",
];

/// `Intl.supportedValuesOf("unit")`: the sanctioned simple unit identifiers
/// (ECMA-402 §6.6.2 Table 1; the testIntl.js `allSimpleSanctionedUnits()`).
pub const SANCTIONED_UNITS: &[&str] = &[
    "acre",
    "bit",
    "byte",
    "celsius",
    "centimeter",
    "day",
    "degree",
    "fahrenheit",
    "fluid-ounce",
    "foot",
    "gallon",
    "gigabit",
    "gigabyte",
    "gram",
    "hectare",
    "hour",
    "inch",
    "kilobit",
    "kilobyte",
    "kilogram",
    "kilometer",
    "liter",
    "megabit",
    "megabyte",
    "meter",
    "microsecond",
    "mile",
    "mile-scandinavian",
    "milliliter",
    "millimeter",
    "millisecond",
    "minute",
    "month",
    "nanosecond",
    "ounce",
    "percent",
    "petabyte",
    "pound",
    "second",
    "stone",
    "terabit",
    "terabyte",
    "week",
    "yard",
    "year",
];

/// IANA time-zone names for `Intl.supportedValuesOf("timeZone")` — the
/// primary zones of `zone1970.tab` plus the common links, the `Etc/GMT±N`
/// offsets, and `UTC`. The fixtures assert the entries are canonicalized and
/// structurally valid (never `Etc/UTC`/`Etc/GMT`) and that the non-continental
/// zones are present (`timeZones-include-non-continental.js`).
pub const SUPPORTED_TIME_ZONES: &[&str] = &[
    "Africa/Abidjan",
    "Africa/Accra",
    "Africa/Addis_Ababa",
    "Africa/Algiers",
    "Africa/Asmara",
    "Africa/Bamako",
    "Africa/Bangui",
    "Africa/Banjul",
    "Africa/Bissau",
    "Africa/Blantyre",
    "Africa/Brazzaville",
    "Africa/Bujumbura",
    "Africa/Cairo",
    "Africa/Casablanca",
    "Africa/Ceuta",
    "Africa/Conakry",
    "Africa/Dakar",
    "Africa/Dar_es_Salaam",
    "Africa/Djibouti",
    "Africa/Douala",
    "Africa/El_Aaiun",
    "Africa/Freetown",
    "Africa/Gaborone",
    "Africa/Harare",
    "Africa/Johannesburg",
    "Africa/Juba",
    "Africa/Kampala",
    "Africa/Khartoum",
    "Africa/Kigali",
    "Africa/Kinshasa",
    "Africa/Lagos",
    "Africa/Libreville",
    "Africa/Lome",
    "Africa/Luanda",
    "Africa/Lubumbashi",
    "Africa/Lusaka",
    "Africa/Malabo",
    "Africa/Maputo",
    "Africa/Maseru",
    "Africa/Mbabane",
    "Africa/Mogadishu",
    "Africa/Monrovia",
    "Africa/Nairobi",
    "Africa/Ndjamena",
    "Africa/Niamey",
    "Africa/Nouakchott",
    "Africa/Ouagadougou",
    "Africa/Porto-Novo",
    "Africa/Sao_Tome",
    "Africa/Tripoli",
    "Africa/Tunis",
    "Africa/Windhoek",
    "America/Adak",
    "America/Anchorage",
    "America/Anguilla",
    "America/Antigua",
    "America/Araguaina",
    "America/Argentina/Buenos_Aires",
    "America/Argentina/Catamarca",
    "America/Argentina/Cordoba",
    "America/Argentina/Jujuy",
    "America/Argentina/La_Rioja",
    "America/Argentina/Mendoza",
    "America/Argentina/Rio_Gallegos",
    "America/Argentina/Salta",
    "America/Argentina/San_Juan",
    "America/Argentina/San_Luis",
    "America/Argentina/Tucuman",
    "America/Argentina/Ushuaia",
    "America/Aruba",
    "America/Asuncion",
    "America/Atikokan",
    "America/Bahia",
    "America/Bahia_Banderas",
    "America/Barbados",
    "America/Belem",
    "America/Belize",
    "America/Blanc-Sablon",
    "America/Boa_Vista",
    "America/Bogota",
    "America/Boise",
    "America/Cambridge_Bay",
    "America/Campo_Grande",
    "America/Cancun",
    "America/Caracas",
    "America/Cayenne",
    "America/Cayman",
    "America/Chicago",
    "America/Chihuahua",
    "America/Ciudad_Juarez",
    "America/Costa_Rica",
    "America/Creston",
    "America/Cuiaba",
    "America/Curacao",
    "America/Danmarkshavn",
    "America/Dawson",
    "America/Dawson_Creek",
    "America/Denver",
    "America/Detroit",
    "America/Dominica",
    "America/Edmonton",
    "America/Eirunepe",
    "America/El_Salvador",
    "America/Fort_Nelson",
    "America/Fortaleza",
    "America/Glace_Bay",
    "America/Goose_Bay",
    "America/Grand_Turk",
    "America/Grenada",
    "America/Guadeloupe",
    "America/Guatemala",
    "America/Guayaquil",
    "America/Guyana",
    "America/Halifax",
    "America/Havana",
    "America/Hermosillo",
    "America/Indiana/Indianapolis",
    "America/Indiana/Knox",
    "America/Indiana/Marengo",
    "America/Indiana/Petersburg",
    "America/Indiana/Tell_City",
    "America/Indiana/Vevay",
    "America/Indiana/Vincennes",
    "America/Indiana/Winamac",
    "America/Inuvik",
    "America/Iqaluit",
    "America/Jamaica",
    "America/Juneau",
    "America/Kentucky/Louisville",
    "America/Kentucky/Monticello",
    "America/La_Paz",
    "America/Lima",
    "America/Los_Angeles",
    "America/Lower_Princes",
    "America/Maceio",
    "America/Managua",
    "America/Manaus",
    "America/Marigot",
    "America/Martinique",
    "America/Matamoros",
    "America/Mazatlan",
    "America/Menominee",
    "America/Merida",
    "America/Metlakatla",
    "America/Mexico_City",
    "America/Miquelon",
    "America/Moncton",
    "America/Monterrey",
    "America/Montevideo",
    "America/Montserrat",
    "America/Nassau",
    "America/New_York",
    "America/Nome",
    "America/Noronha",
    "America/North_Dakota/Beulah",
    "America/North_Dakota/Center",
    "America/North_Dakota/New_Salem",
    "America/Nuuk",
    "America/Ojinaga",
    "America/Panama",
    "America/Paramaribo",
    "America/Phoenix",
    "America/Port-au-Prince",
    "America/Port_of_Spain",
    "America/Porto_Velho",
    "America/Puerto_Rico",
    "America/Punta_Arenas",
    "America/Rankin_Inlet",
    "America/Recife",
    "America/Regina",
    "America/Resolute",
    "America/Rio_Branco",
    "America/Santarem",
    "America/Santiago",
    "America/Santo_Domingo",
    "America/Sao_Paulo",
    "America/Scoresbysund",
    "America/Sitka",
    "America/St_Barthelemy",
    "America/St_Johns",
    "America/St_Kitts",
    "America/St_Lucia",
    "America/St_Thomas",
    "America/St_Vincent",
    "America/Swift_Current",
    "America/Tegucigalpa",
    "America/Thule",
    "America/Tijuana",
    "America/Toronto",
    "America/Tortola",
    "America/Vancouver",
    "America/Whitehorse",
    "America/Winnipeg",
    "America/Yakutat",
    "Antarctica/Casey",
    "Antarctica/Davis",
    "Antarctica/DumontDUrville",
    "Antarctica/Macquarie",
    "Antarctica/Mawson",
    "Antarctica/McMurdo",
    "Antarctica/Palmer",
    "Antarctica/Rothera",
    "Antarctica/Syowa",
    "Antarctica/Troll",
    "Antarctica/Vostok",
    "Arctic/Longyearbyen",
    "Asia/Aden",
    "Asia/Almaty",
    "Asia/Amman",
    "Asia/Anadyr",
    "Asia/Aqtau",
    "Asia/Aqtobe",
    "Asia/Ashgabat",
    "Asia/Atyrau",
    "Asia/Baghdad",
    "Asia/Bahrain",
    "Asia/Baku",
    "Asia/Bangkok",
    "Asia/Barnaul",
    "Asia/Beirut",
    "Asia/Bishkek",
    "Asia/Brunei",
    "Asia/Chita",
    "Asia/Choibalsan",
    "Asia/Colombo",
    "Asia/Damascus",
    "Asia/Dhaka",
    "Asia/Dili",
    "Asia/Dubai",
    "Asia/Dushanbe",
    "Asia/Famagusta",
    "Asia/Gaza",
    "Asia/Hebron",
    "Asia/Ho_Chi_Minh",
    "Asia/Hong_Kong",
    "Asia/Hovd",
    "Asia/Irkutsk",
    "Asia/Jakarta",
    "Asia/Jayapura",
    "Asia/Jerusalem",
    "Asia/Kabul",
    "Asia/Kamchatka",
    "Asia/Karachi",
    "Asia/Kathmandu",
    "Asia/Khandyga",
    "Asia/Kolkata",
    "Asia/Krasnoyarsk",
    "Asia/Kuala_Lumpur",
    "Asia/Kuching",
    "Asia/Kuwait",
    "Asia/Macau",
    "Asia/Magadan",
    "Asia/Makassar",
    "Asia/Manila",
    "Asia/Muscat",
    "Asia/Nicosia",
    "Asia/Novokuznetsk",
    "Asia/Novosibirsk",
    "Asia/Omsk",
    "Asia/Oral",
    "Asia/Phnom_Penh",
    "Asia/Pontianak",
    "Asia/Pyongyang",
    "Asia/Qatar",
    "Asia/Qostanay",
    "Asia/Qyzylorda",
    "Asia/Riyadh",
    "Asia/Sakhalin",
    "Asia/Samarkand",
    "Asia/Seoul",
    "Asia/Shanghai",
    "Asia/Singapore",
    "Asia/Srednekolymsk",
    "Asia/Taipei",
    "Asia/Tashkent",
    "Asia/Tbilisi",
    "Asia/Tehran",
    "Asia/Thimphu",
    "Asia/Tokyo",
    "Asia/Tomsk",
    "Asia/Ulaanbaatar",
    "Asia/Urumqi",
    "Asia/Ust-Nera",
    "Asia/Vientiane",
    "Asia/Vladivostok",
    "Asia/Yakutsk",
    "Asia/Yangon",
    "Asia/Yekaterinburg",
    "Asia/Yerevan",
    "Atlantic/Azores",
    "Atlantic/Bermuda",
    "Atlantic/Canary",
    "Atlantic/Cape_Verde",
    "Atlantic/Faroe",
    "Atlantic/Madeira",
    "Atlantic/Reykjavik",
    "Atlantic/South_Georgia",
    "Atlantic/St_Helena",
    "Atlantic/Stanley",
    "Australia/Adelaide",
    "Australia/Brisbane",
    "Australia/Broken_Hill",
    "Australia/Darwin",
    "Australia/Eucla",
    "Australia/Hobart",
    "Australia/Lindeman",
    "Australia/Lord_Howe",
    "Australia/Melbourne",
    "Australia/Perth",
    "Australia/Sydney",
    "Etc/GMT+1",
    "Etc/GMT+10",
    "Etc/GMT+11",
    "Etc/GMT+12",
    "Etc/GMT+2",
    "Etc/GMT+3",
    "Etc/GMT+4",
    "Etc/GMT+5",
    "Etc/GMT+6",
    "Etc/GMT+7",
    "Etc/GMT+8",
    "Etc/GMT+9",
    "Etc/GMT-1",
    "Etc/GMT-10",
    "Etc/GMT-11",
    "Etc/GMT-12",
    "Etc/GMT-13",
    "Etc/GMT-14",
    "Etc/GMT-2",
    "Etc/GMT-3",
    "Etc/GMT-4",
    "Etc/GMT-5",
    "Etc/GMT-6",
    "Etc/GMT-7",
    "Etc/GMT-8",
    "Etc/GMT-9",
    "Europe/Amsterdam",
    "Europe/Andorra",
    "Europe/Astrakhan",
    "Europe/Athens",
    "Europe/Belgrade",
    "Europe/Berlin",
    "Europe/Bratislava",
    "Europe/Brussels",
    "Europe/Bucharest",
    "Europe/Budapest",
    "Europe/Busingen",
    "Europe/Chisinau",
    "Europe/Copenhagen",
    "Europe/Dublin",
    "Europe/Gibraltar",
    "Europe/Guernsey",
    "Europe/Helsinki",
    "Europe/Isle_of_Man",
    "Europe/Istanbul",
    "Europe/Jersey",
    "Europe/Kaliningrad",
    "Europe/Kirov",
    "Europe/Kyiv",
    "Europe/Lisbon",
    "Europe/Ljubljana",
    "Europe/London",
    "Europe/Luxembourg",
    "Europe/Madrid",
    "Europe/Malta",
    "Europe/Mariehamn",
    "Europe/Minsk",
    "Europe/Moscow",
    "Europe/Oslo",
    "Europe/Paris",
    "Europe/Podgorica",
    "Europe/Prague",
    "Europe/Riga",
    "Europe/Rome",
    "Europe/Samara",
    "Europe/San_Marino",
    "Europe/Sarajevo",
    "Europe/Saratov",
    "Europe/Simferopol",
    "Europe/Skopje",
    "Europe/Sofia",
    "Europe/Stockholm",
    "Europe/Tallinn",
    "Europe/Tirane",
    "Europe/Ulyanovsk",
    "Europe/Vaduz",
    "Europe/Vatican",
    "Europe/Vienna",
    "Europe/Vilnius",
    "Europe/Volgograd",
    "Europe/Warsaw",
    "Europe/Zagreb",
    "Europe/Zurich",
    "Indian/Antananarivo",
    "Indian/Chagos",
    "Indian/Christmas",
    "Indian/Cocos",
    "Indian/Comoro",
    "Indian/Kerguelen",
    "Indian/Mahe",
    "Indian/Maldives",
    "Indian/Mauritius",
    "Indian/Mayotte",
    "Indian/Reunion",
    "Pacific/Apia",
    "Pacific/Auckland",
    "Pacific/Bougainville",
    "Pacific/Chatham",
    "Pacific/Chuuk",
    "Pacific/Easter",
    "Pacific/Efate",
    "Pacific/Enderbury",
    "Pacific/Fakaofo",
    "Pacific/Fiji",
    "Pacific/Funafuti",
    "Pacific/Galapagos",
    "Pacific/Gambier",
    "Pacific/Guadalcanal",
    "Pacific/Guam",
    "Pacific/Honolulu",
    "Pacific/Kanton",
    "Pacific/Kiritimati",
    "Pacific/Kosrae",
    "Pacific/Kwajalein",
    "Pacific/Majuro",
    "Pacific/Marquesas",
    "Pacific/Midway",
    "Pacific/Nauru",
    "Pacific/Niue",
    "Pacific/Norfolk",
    "Pacific/Noumea",
    "Pacific/Pago_Pago",
    "Pacific/Palau",
    "Pacific/Pitcairn",
    "Pacific/Pohnpei",
    "Pacific/Port_Moresby",
    "Pacific/Rarotonga",
    "Pacific/Saipan",
    "Pacific/Tahiti",
    "Pacific/Tarawa",
    "Pacific/Tongatapu",
    "Pacific/Wake",
    "Pacific/Wallis",
    "UTC",
];

/// The `nu`-relevant locales are resolved through the per-locale records in
/// `crate::builtins::intl::number_format`; this list is the
/// `[[AvailableLocales]]` of `%Intl.NumberFormat%` (the base languages and
/// the exact tags the corpus requests with locale-specific data). Lookup
/// falls back to the base language, then to `en`.
pub const NUMBER_FORMAT_LOCALES: &[&str] = &[
    "aa",
    "ab",
    "af",
    "ak",
    "am",
    "ar",
    "ar-EG",
    "as",
    "az",
    "be",
    "bg",
    "bg-BG",
    "bn",
    "bs",
    "ca",
    "ceb",
    "ckb",
    "co",
    "cs",
    "cs-CZ",
    "cy",
    "da",
    "de",
    "de-AT",
    "de-CH",
    "de-DE",
    "dz",
    "ee",
    "el",
    "en",
    "en-GB",
    "en-IN",
    "en-US",
    "eo",
    "es",
    "es-419",
    "es-ES",
    "et",
    "eu",
    "fa",
    "fi",
    "fil",
    "fr",
    "fr-CA",
    "fr-FR",
    "fy",
    "ga",
    "gd",
    "gl",
    "gu",
    "gv",
    "ha",
    "haw",
    "he",
    "he-IL",
    "hi",
    "hi-IN",
    "hr",
    "ht",
    "hu",
    "hy",
    "id",
    "ig",
    "is",
    "it",
    "it-IT",
    "ja",
    "ja-JP",
    "jv",
    "ka",
    "kk",
    "km",
    "kn",
    "ko",
    "ko-KR",
    "ku",
    "ky",
    "la",
    "lb",
    "lg",
    "ln",
    "lo",
    "lt",
    "lv",
    "mg",
    "mi",
    "mk",
    "ml",
    "mn",
    "mr",
    "ms",
    "mt",
    "my",
    "nb",
    "nd",
    "ne",
    "nl",
    "nn",
    "no",
    "no-bok",
    "ny",
    "oc",
    "om",
    "or",
    "pa",
    "pl",
    "ps",
    "pt",
    "pt-BR",
    "pt-PT",
    "qu",
    "rm",
    "ro",
    "ru",
    "ru-RU",
    "rw",
    "sd",
    "si",
    "sk",
    "sl",
    "sn",
    "so",
    "sq",
    "sr",
    "sr-Latn",
    "st",
    "su",
    "sv",
    "sw",
    "ta",
    "te",
    "tg",
    "th",
    "th-TH",
    "ti",
    "tk",
    "tl",
    "tr",
    "ts",
    "tt",
    "ug",
    "uk",
    "ur",
    "uz",
    "vi",
    "wo",
    "xh",
    "yi",
    "yo",
    "zh",
    "zh-CN",
    "zh-Hans-CN",
    "zh-Hant-TW",
    "zh-TW",
    "zu",
];

/// A compact-notation entry: the exponent power and the display patterns
/// (with their affix strings). The pattern carries the separator literals
/// around `{number}` and `{compactSymbol}`/`{compactName}`; the affix is the
/// symbol/name string the placeholder resolves to. An empty affix means "no
/// affix" (the exponent collapses to 0 — the German short 10^3..10^5 gaps).
#[derive(Debug, Clone, Copy)]
pub struct CompactEntry {
    pub power: i32,
    pub short: &'static str,
    pub short_affix: &'static str,
    pub long: &'static str,
    pub long_affix: &'static str,
}

/// A unit entry: per display, the pattern (which carries the separator
/// literals around `{number}` and the `{unitPrefix}`/`{unitSuffix}`
/// placeholders) and the prefix/suffix strings the placeholders resolve to.
#[derive(Debug, Clone, Copy)]
pub struct UnitDisplay {
    pub pattern: &'static str,
    pub prefix: &'static str,
    pub suffix: &'static str,
    /// The plural (other-form) suffix, chosen when the formatted value is
    /// not 1/-1 (CLDR en unit patterns pluralize: "1 day" / "2 days";
    /// abbreviations like "hr" and compounds like "km/h" are invariant).
    pub plural_suffix: &'static str,
}

#[derive(Debug, Clone, Copy)]
pub struct UnitEntry {
    pub unit: &'static str,
    pub narrow: UnitDisplay,
    pub short: UnitDisplay,
    pub long: UnitDisplay,
}

/// The per-locale data record (ECMA-402 §16.2.3 LocaleData). The currency
/// and unit patterns are the raw sign-independent templates; the sign
/// variants are derived in `number_format.rs`.
#[derive(Debug, Clone, Copy)]
pub struct NumberLocaleData {
    pub decimal: &'static str,
    pub group: &'static str,
    pub percent: &'static str,
    pub nan: &'static str,
    pub infinity: &'static str,
    /// The percent style pattern (contains `{number}` and `{percentSign}`).
    pub percent_pattern: &'static str,
    /// Currency patterns, one per (display, sign-category) in the order
    /// [symbol/standard positive, negative, accounting-negative,
    /// code positive, code negative, name positive, name negative].
    pub currency_patterns: [&'static str; 7],
    pub units: &'static [UnitEntry],
    pub primary_group: u32,
    pub secondary_group: u32,
    pub compact: &'static [CompactEntry],
    pub currencies: &'static [(&'static str, &'static str, &'static str)],
    /// The unit/number separator the formatRange tests read dynamically.
    pub range_separator: &'static str,
    /// The separator when the range is collapsed (en-US: "–" vs " – ";
    /// pinned by formatRange/en-US.js and formatRangeToParts/en-US.js).
    pub range_separator_collapsed: &'static str,
    pub approximately: &'static str,
}

/// A unit entry constructor (the 13 arguments are the three display sets of
/// pattern/prefix/suffix plus the plural suffix; a data-table helper).
#[allow(clippy::too_many_arguments)]
const fn unit(
    unit: &'static str,
    narrow_pattern: &'static str,
    narrow_prefix: &'static str,
    narrow_suffix: &'static str,
    narrow_plural: &'static str,
    short_pattern: &'static str,
    short_prefix: &'static str,
    short_suffix: &'static str,
    short_plural: &'static str,
    long_pattern: &'static str,
    long_prefix: &'static str,
    long_suffix: &'static str,
    long_plural: &'static str,
) -> UnitEntry {
    UnitEntry {
        unit,
        narrow: UnitDisplay {
            pattern: narrow_pattern,
            prefix: narrow_prefix,
            suffix: narrow_suffix,
            plural_suffix: narrow_plural,
        },
        short: UnitDisplay {
            pattern: short_pattern,
            prefix: short_prefix,
            suffix: short_suffix,
            plural_suffix: short_plural,
        },
        long: UnitDisplay {
            pattern: long_pattern,
            prefix: long_prefix,
            suffix: long_suffix,
            plural_suffix: long_plural,
        },
    }
}

const fn compact(
    power: i32,
    short: &'static str,
    short_affix: &'static str,
    long: &'static str,
    long_affix: &'static str,
) -> CompactEntry {
    CompactEntry {
        power,
        short,
        short_affix,
        long,
        long_affix,
    }
}

/// The currency template patterns use these placeholders:
/// `{number}`, `{minusSign}`, `{plusSign}`, `{currencyPrefix}`,
/// `{currencySuffix}`, `{currencyCode}`, `{currencyName}`.
const EN_US_CURRENCY: [&str; 7] = [
    "{currencyPrefix}{number}",
    "{minusSign}{currencyPrefix}{number}",
    "({currencyPrefix}{number})",
    "{currencyCode}{number}",
    "{minusSign}{currencyCode}{number}",
    "{number} {currencyName}",
    "{minusSign}{number} {currencyName}",
];

const EN_US_UNITS: &[UnitEntry] = &[
    unit(
        "kilometer-per-hour",
        "{number}{unitSuffix}",
        "",
        "km/h",
        "km/h",
        "{number} {unitSuffix}",
        "",
        "km/h",
        "km/h",
        "{number} {unitSuffix}",
        "",
        "kilometers per hour",
        "kilometers per hour",
    ),
    unit(
        "percent",
        "{number}{unitSuffix}",
        "",
        "%",
        "%",
        "{number}{unitSuffix}",
        "",
        "%",
        "%",
        "{number} {unitSuffix}",
        "",
        "percent",
        "percent",
    ),
    unit(
        "year",
        "{number}{unitSuffix}",
        "",
        "yr",
        "yr",
        "{number} {unitSuffix}",
        "",
        "yr",
        "yr",
        "{number} {unitSuffix}",
        "",
        "year",
        "years",
    ),
    unit(
        "month",
        "{number}{unitSuffix}",
        "",
        "mo",
        "mo",
        "{number} {unitSuffix}",
        "",
        "mo",
        "mo",
        "{number} {unitSuffix}",
        "",
        "month",
        "months",
    ),
    unit(
        "week",
        "{number}{unitSuffix}",
        "",
        "wk",
        "wk",
        "{number} {unitSuffix}",
        "",
        "wk",
        "wk",
        "{number} {unitSuffix}",
        "",
        "week",
        "weeks",
    ),
    unit(
        "day",
        "{number}{unitSuffix}",
        "",
        "day",
        "days",
        "{number} {unitSuffix}",
        "",
        "day",
        "days",
        "{number} {unitSuffix}",
        "",
        "day",
        "days",
    ),
    unit(
        "hour",
        "{number}{unitSuffix}",
        "",
        "hr",
        "hr",
        "{number} {unitSuffix}",
        "",
        "hr",
        "hr",
        "{number} {unitSuffix}",
        "",
        "hour",
        "hours",
    ),
    unit(
        "minute",
        "{number}{unitSuffix}",
        "",
        "min",
        "min",
        "{number} {unitSuffix}",
        "",
        "min",
        "min",
        "{number} {unitSuffix}",
        "",
        "minute",
        "minutes",
    ),
    unit(
        "second",
        "{number}{unitSuffix}",
        "",
        "sec",
        "sec",
        "{number} {unitSuffix}",
        "",
        "sec",
        "sec",
        "{number} {unitSuffix}",
        "",
        "second",
        "seconds",
    ),
    unit(
        "millisecond",
        "{number}{unitSuffix}",
        "",
        "ms",
        "ms",
        "{number} {unitSuffix}",
        "",
        "ms",
        "ms",
        "{number} {unitSuffix}",
        "",
        "millisecond",
        "milliseconds",
    ),
    unit(
        "microsecond",
        "{number}{unitSuffix}",
        "",
        "μs",
        "μs",
        "{number} {unitSuffix}",
        "",
        "μs",
        "μs",
        "{number} {unitSuffix}",
        "",
        "microsecond",
        "microseconds",
    ),
    unit(
        "nanosecond",
        "{number}{unitSuffix}",
        "",
        "ns",
        "ns",
        "{number} {unitSuffix}",
        "",
        "ns",
        "ns",
        "{number} {unitSuffix}",
        "",
        "nanosecond",
        "nanoseconds",
    ),
];

const EN_US_CURRENCIES: &[(&str, &str, &str)] = &[
    ("USD", "$", "US dollars"),
    ("EUR", "€", "euros"),
    ("GBP", "£", "British pounds"),
    ("JPY", "¥", "Japanese yen"),
    ("CNY", "CN¥", "Chinese yuan"),
    ("INR", "₹", "Indian rupees"),
];

const EN_US_COMPACT: &[CompactEntry] = &[
    compact(
        3,
        "{number}{compactSymbol}",
        "K",
        "{number} {compactName}",
        "thousand",
    ),
    compact(
        6,
        "{number}{compactSymbol}",
        "M",
        "{number} {compactName}",
        "million",
    ),
    compact(
        9,
        "{number}{compactSymbol}",
        "B",
        "{number} {compactName}",
        "billion",
    ),
    compact(
        12,
        "{number}{compactSymbol}",
        "T",
        "{number} {compactName}",
        "trillion",
    ),
];

const EN_US: NumberLocaleData = NumberLocaleData {
    decimal: ".",
    group: ",",
    percent: "%",
    nan: "NaN",
    infinity: "∞",
    percent_pattern: "{number}{percentSign}",
    currency_patterns: EN_US_CURRENCY,
    units: EN_US_UNITS,
    primary_group: 3,
    secondary_group: 3,
    compact: EN_US_COMPACT,
    currencies: EN_US_CURRENCIES,
    range_separator: " – ",
    range_separator_collapsed: "–",
    approximately: "~",
};

const EN_IN: NumberLocaleData = NumberLocaleData {
    decimal: ".",
    group: ",",
    percent: "%",
    nan: "NaN",
    infinity: "∞",
    percent_pattern: "{number}{percentSign}",
    currency_patterns: EN_US_CURRENCY,
    units: EN_US_UNITS,
    // Indian grouping: 12,34,56,789 — the last group is 3, the rest 2.
    primary_group: 3,
    secondary_group: 2,
    compact: &[
        compact(
            3,
            "{number}{compactSymbol}",
            "K",
            "{number} {compactName}",
            "thousand",
        ),
        compact(
            5,
            "{number}{compactSymbol}",
            "L",
            "{number} {compactName}",
            "lakh",
        ),
        compact(
            7,
            "{number}{compactSymbol}",
            "Cr",
            "{number} {compactName}",
            "crore",
        ),
    ],
    currencies: EN_US_CURRENCIES,
    range_separator: " – ",
    range_separator_collapsed: "–",
    approximately: "~",
};

const DE_DE_CURRENCY: [&str; 7] = [
    "{number}\u{a0}{currencySuffix}",
    "{minusSign}{number}\u{a0}{currencySuffix}",
    "{minusSign}{number}\u{a0}{currencySuffix}",
    "{number}\u{a0}{currencyCode}",
    "{minusSign}{number}\u{a0}{currencyCode}",
    "{number} {currencyName}",
    "{minusSign}{number} {currencyName}",
];

const DE_DE_UNITS: &[UnitEntry] = &[unit(
    "kilometer-per-hour",
    "{number} {unitSuffix}",
    "",
    "km/h",
    "km/h",
    "{number} {unitSuffix}",
    "",
    "km/h",
    "km/h",
    "{number} {unitSuffix}",
    "",
    "Kilometer pro Stunde",
    "Kilometer pro Stunde",
)];

const DE_DE_COMPACT: &[CompactEntry] = &[
    // 10^3..10^5 have no short affix (the fixtures pin 98765 → "98.765"
    // under min2 grouping); the long form has "Tausend".
    compact(3, "", "", "{number} {compactName}", "Tausend"),
    compact(
        6,
        "{number}\u{a0}{compactSymbol}",
        "Mio.",
        "{number} {compactName}",
        "Millionen",
    ),
    compact(
        9,
        "{number}\u{a0}{compactSymbol}",
        "Mrd.",
        "{number} {compactName}",
        "Milliarden",
    ),
    compact(
        12,
        "{number}\u{a0}{compactSymbol}",
        "Bio.",
        "{number} {compactName}",
        "Billionen",
    ),
];

const DE_DE: NumberLocaleData = NumberLocaleData {
    decimal: ",",
    group: ".",
    percent: "%",
    nan: "NaN",
    infinity: "∞",
    percent_pattern: "{number}\u{a0}{percentSign}",
    currency_patterns: DE_DE_CURRENCY,
    units: DE_DE_UNITS,
    primary_group: 3,
    secondary_group: 3,
    compact: DE_DE_COMPACT,
    currencies: &[("EUR", "€", "Euro"), ("USD", "$", "US-Dollar")],
    range_separator: " – ",
    range_separator_collapsed: " – ",
    approximately: "~",
};

const JA_JP_UNITS: &[UnitEntry] = &[unit(
    "kilometer-per-hour",
    "{number}{unitSuffix}",
    "",
    "km/h",
    "km/h",
    "{number}{unitSuffix}",
    "",
    "km/h",
    "km/h",
    "{unitPrefix} {number} {unitSuffix}",
    "時速",
    "キロメートル",
    "キロメートル",
)];

const JA_JP_COMPACT: &[CompactEntry] = &[
    compact(
        4,
        "{number}{compactSymbol}",
        "万",
        "{number}{compactSymbol}",
        "万",
    ),
    compact(
        8,
        "{number}{compactSymbol}",
        "億",
        "{number}{compactSymbol}",
        "億",
    ),
];

const JA_JP: NumberLocaleData = NumberLocaleData {
    decimal: ".",
    group: ",",
    percent: "%",
    nan: "NaN",
    infinity: "∞",
    percent_pattern: "{number}{percentSign}",
    currency_patterns: EN_US_CURRENCY,
    units: JA_JP_UNITS,
    primary_group: 3,
    secondary_group: 3,
    compact: JA_JP_COMPACT,
    currencies: &[("JPY", "￥", "円"), ("USD", "$", "米ドル")],
    range_separator: "～",
    range_separator_collapsed: "～",
    approximately: "約",
};

const KO_KR_UNITS: &[UnitEntry] = &[unit(
    "kilometer-per-hour",
    "{number}{unitSuffix}",
    "",
    "km/h",
    "km/h",
    "{number}{unitSuffix}",
    "",
    "km/h",
    "km/h",
    "{unitPrefix} {number}{unitSuffix}",
    "시속",
    "킬로미터",
    "킬로미터",
)];

const KO_KR_COMPACT: &[CompactEntry] = &[
    compact(
        3,
        "{number}{compactSymbol}",
        "천",
        "{number}{compactSymbol}",
        "천",
    ),
    compact(
        4,
        "{number}{compactSymbol}",
        "만",
        "{number}{compactSymbol}",
        "만",
    ),
    compact(
        8,
        "{number}{compactSymbol}",
        "억",
        "{number}{compactSymbol}",
        "억",
    ),
];

const KO_KR: NumberLocaleData = NumberLocaleData {
    decimal: ".",
    group: ",",
    percent: "%",
    nan: "NaN",
    infinity: "∞",
    percent_pattern: "{number}{percentSign}",
    currency_patterns: EN_US_CURRENCY,
    units: KO_KR_UNITS,
    primary_group: 3,
    secondary_group: 3,
    compact: KO_KR_COMPACT,
    currencies: &[("KRW", "₩", "대한민국 원"), ("USD", "US$", "미국 달러")],
    range_separator: " ~ ",
    range_separator_collapsed: " ~ ",
    approximately: "약",
};

const ZH_TW_UNITS: &[UnitEntry] = &[unit(
    "kilometer-per-hour",
    "{number}{unitSuffix}",
    "",
    "公里/小時",
    "公里/小時",
    "{number}{unitSuffix}",
    "",
    "公里/小時",
    "公里/小時",
    "{unitPrefix}{number}{unitSuffix}",
    "每小時",
    "公里",
    "公里",
)];

const ZH_TW_COMPACT: &[CompactEntry] = &[
    compact(
        4,
        "{number}{compactSymbol}",
        "萬",
        "{number}{compactSymbol}",
        "萬",
    ),
    compact(
        8,
        "{number}{compactSymbol}",
        "億",
        "{number}{compactSymbol}",
        "億",
    ),
];

const ZH_TW: NumberLocaleData = NumberLocaleData {
    decimal: ".",
    group: ",",
    percent: "%",
    nan: "非數值",
    infinity: "∞",
    percent_pattern: "{number}{percentSign}",
    currency_patterns: EN_US_CURRENCY,
    units: ZH_TW_UNITS,
    primary_group: 3,
    secondary_group: 3,
    compact: ZH_TW_COMPACT,
    currencies: &[("TWD", "NT$", "新台幣"), ("USD", "US$", "美元")],
    range_separator: " – ",
    range_separator_collapsed: "–",
    approximately: "~",
};

const ZH_CN: NumberLocaleData = NumberLocaleData {
    decimal: ".",
    group: ",",
    percent: "%",
    nan: "NaN",
    infinity: "∞",
    percent_pattern: "{number}{percentSign}",
    currency_patterns: EN_US_CURRENCY,
    units: EN_US_UNITS,
    primary_group: 3,
    secondary_group: 3,
    compact: &[
        compact(
            4,
            "{number}{compactSymbol}",
            "万",
            "{number}{compactSymbol}",
            "万",
        ),
        compact(
            8,
            "{number}{compactSymbol}",
            "亿",
            "{number}{compactSymbol}",
            "亿",
        ),
    ],
    currencies: &[("CNY", "¥", "人民币"), ("USD", "$", "美元")],
    range_separator: "–",
    range_separator_collapsed: "–",
    approximately: "约",
};

const PT_PT_CURRENCY: [&str; 7] = [
    "{number}\u{a0}{currencySuffix}",
    "{minusSign}{number}\u{a0}{currencySuffix}",
    "{minusSign}{number}\u{a0}{currencySuffix}",
    "{number}\u{a0}{currencyCode}",
    "{minusSign}{number}\u{a0}{currencyCode}",
    "{number} {currencyName}",
    "{minusSign}{number} {currencyName}",
];

const PT_PT: NumberLocaleData = NumberLocaleData {
    decimal: ",",
    group: "\u{a0}",
    percent: "%",
    nan: "NaN",
    infinity: "∞",
    percent_pattern: "{number}\u{a0}{percentSign}",
    currency_patterns: PT_PT_CURRENCY,
    units: EN_US_UNITS,
    primary_group: 3,
    secondary_group: 3,
    compact: &[
        compact(
            3,
            "{number}\u{a0}{compactSymbol}",
            "mil",
            "{number} {compactName}",
            "mil",
        ),
        compact(
            6,
            "{number}\u{a0}{compactSymbol}",
            "M",
            "{number} {compactName}",
            "milhões",
        ),
    ],
    currencies: &[("EUR", "€", "euros"), ("USD", "$", "dólares americanos")],
    range_separator: " - ",
    range_separator_collapsed: " - ",
    approximately: "~",
};

/// The generic record for the remaining base languages: en-US separators and
/// the en-US patterns.
const GENERIC: NumberLocaleData = NumberLocaleData {
    decimal: ".",
    group: ",",
    percent: "%",
    nan: "NaN",
    infinity: "∞",
    percent_pattern: "{number}{percentSign}",
    currency_patterns: EN_US_CURRENCY,
    units: EN_US_UNITS,
    primary_group: 3,
    secondary_group: 3,
    compact: EN_US_COMPACT,
    currencies: EN_US_CURRENCIES,
    range_separator: " – ",
    range_separator_collapsed: "–",
    approximately: "~",
};

/// Look up the locale data record: the exact tag, then the base language,
/// then the generic record (the plan's Cut 2 spike — hand-written data for
/// the pinned locales; the rest inherit the generic decimal surface).
pub fn locale_data(locale: &str) -> &'static NumberLocaleData {
    match locale {
        "en" | "en-US" | "en-GB" => &EN_US,
        "en-IN" => &EN_IN,
        "de" | "de-DE" | "de-AT" | "de-CH" => &DE_DE,
        "ja" | "ja-JP" => &JA_JP,
        "ko" | "ko-KR" => &KO_KR,
        "zh" | "zh-TW" | "zh-Hant-TW" => &ZH_TW,
        "zh-CN" | "zh-Hans-CN" => &ZH_CN,
        "pt" | "pt-PT" => &PT_PT,
        "pl" | "pl-PL" => &PT_PT,
        _ => &GENERIC,
    }
}
