[workspace]
resolver = "2"
members = [
    "crates/unicode",
    "crates/crux",
    "crates/syntax",
    "crates/lexer",
    "crates/parser",
    "crates/regexp",
    "crates/runtime",
    "crates/ffi",
    "crates/cli",
    "crates/test262",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
